session_name: welcomemedia
environment:
  EDITOR: /usr/bin/vim
windows:
  - window_name: system
    layout: tiled
    automatic_rename: false
    start_directory: /Developer
    panes:
      - htop
      - rainbowstream
      - task
      - blank
  - window_name: wmnews
    layout: 5424,167x43,0,0{111x43,0,0,0,55x43,112,0[55x21,112,0,2,55x21,112,22,3]}
    automatic_rename: false 
    start_directory: /Developer/setion
    shell_command_before: venv setion
    panes:
      - shell_command:
        - vim
        focus: true
      - shell_command: ./manage.py runserver
      - git status
  - window_name: janasegetti
    layout: 5424,167x43,0,0{111x43,0,0,0,55x43,112,0[55x21,112,0,2,55x21,112,22,3]}
    automatic_rename: false
    start_directory: /Developer/janasegetti
    shell_command_before: venv janasegetti
    panes:
      - shell_command:
        - vim
        focus: true
      - shell_command: ./manage.py runserver
      - git status

